PHP 8.1: fix passing null to non-nullable deprecation
Automattic/nginx-http-concat pull request #72
Opened 2023-01-18 00:36 UTC by mustafauysal

It seems `rtrim()` expects to be passed a string, and it is not a nullable parameter on PHP 8.1. Passing `null` results `rtrim(): Passing null to parameter #1 ($string) of type string is deprecated` notice.

Ref:
* https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg

2023-09-18 10:44 UTC, lomeraniel commented
Noting here that a VIP customer is facing this issue: 

```
"rtrim(): Passing null to parameter #1 ($string) of type string is deprecated"

Trace from QM:
wp-includes/formatting.php:2827
rtrim()
wp-includes/formatting.php:2827
untrailingslashit()
wp-includes/formatting.php:2812
trailingslashit()
wp-content/mu-plugins/http-concat/concat-utils.php:27
WPCOM_Concat_Utils::realpath()
wp-content/mu-plugins/http-concat/cssconcat.php:84
WPcom_CSS_Concat->do_items()
wp-includes/functions.wp-styles.php:68
wp_print_styles()
wp-includes/class-wp-hook.php:310
do_action('wp_head')
wp-includes/general-template.php:3053
wp_head()
wp-content/themes/dispatch/header.php:48
load_template('wp-content/themes/dispatch/header.php')
wp-includes/template.php:720
locate_template()
wp-includes/general-template.php:48
get_header()
wp-content/themes/dispatch/front-page.php:15
```

2023-09-18 17:01 UTC, mustafauysal commented
@lomeraniel could you give it a try on the root domain without having a trailingslash? ( e.g. `example.com` without `/` at the end )

2023-09-21 15:12 UTC, bytesizeguru commented
Another VIP customer reporting the same issue today:

```
Deprecated rtrim(): Passing null to parameter [#1](https://wordpressvip.zendesk.com/agent/tickets/1) ($string) of type string is deprecated 183
wp-includes/formatting.php:2827
MU Plugin: http-concat
wp-includes/formatting.php:2827
rtrim()
wp-includes/formatting.php:2827
untrailingslashit()
wp-includes/formatting.php:2812
trailingslashit()
wp-content/mu-plugins/http-concat/concat-utils.php:27
WPCOM_Concat_Utils::realpath()
wp-content/mu-plugins/http-concat/cssconcat.php:84
WPcom_CSS_Concat->do_items()
wp-includes/script-loader.php:2244
print_admin_styles()
wp-includes/class-wp-hook.php:310
do_action('admin_print_styles')
wp-admin/admin-header.php:132
```

2023-09-29 18:24 UTC, rodruiz commented
VIP customer here. We are having the same issue on our dev environment.

```log
wp-includes/formatting.php:2827
rtrim()
wp-includes/formatting.php:2827
untrailingslashit()
wp-includes/formatting.php:2812
trailingslashit()
wp-content/mu-plugins/http-concat/concat-utils.php:27
WPCOM_Concat_Utils::realpath()
wp-content/mu-plugins/http-concat/cssconcat.php:84
WPcom_CSS_Concat->do_items()
wp-includes/functions.wp-styles.php:68
wp_print_styles()
wp-includes/class-wp-hook.php:310
do_action('wp_head')
wp-includes/general-template.php:3053
wp_head()
wp-content/themes/rjth2019/header.php:44
load_template('wp-content/themes/rjth2019/header.php')
wp-includes/template.php:720
locate_template()
wp-includes/general-template.php:48
get_header()
wp-content/themes/rjth2019/single-post.php:21
```

2023-09-30 12:51 UTC, emreerkan approved these changes
LGTM

2023-10-04 18:04 UTC, rebeccahum requested changes

2023-10-04 18:04 UTC, rebeccahum commented on concat-utils.php
> +		$site_url_path = is_null( $site_url_path ) ? '/' : trailingslashit( $site_url_path );
Can we just return an empty string instead of `/` since that's what was the return value in previous PHP versions?

2023-10-04 18:05 UTC, rebeccahum commented on concat-utils.php
> +		$site_url_path = is_null( $site_url_path ) ? '/' : trailingslashit( $site_url_path );
```suggestion
		$site_url_path = trailingslashit( $site_url_path ?? '' );
```

2023-10-04 18:08 UTC, rebeccahum approved these changes

2023-10-04 18:09 UTC, merged

2023-10-04 18:41 UTC, rebeccahum commented
Reproduced, fix works thanks